server:
  port: 8010
spring:
  data:
    redis:
      port: 6379
      host: localhost
  profiles:
    active: local
  application:
    name: chatting
  cloud:
    zookeeper:
      connect-string: localhost:22181
      discovery:
        enabled: true
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN

#spring:
#  application:
#    name: chatting-service
#  profiles:
#    active: local
#
#eureka:
##  instance:
##    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:ㅎ
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka